import 'dart:async';
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:provider/provider.dart';
import 'package:geolocator/geolocator.dart';

import '../../../../core/constants/app_colors.dart';
import '../../../../core/services/local_storage_service.dart';
import '../../../../core/widgets/custom_app_bar.dart';
import '../../../../core/widgets/custom_text_field.dart';
import '../../../../core/widgets/loading_overlay.dart';
import '../providers/school_provider.dart';
import '../../../auth/presentation/providers/auth_provider.dart';

class AddSchoolPage extends StatefulWidget {
  const AddSchoolPage({super.key});

  @override
  State<AddSchoolPage> createState() => _AddSchoolPageState();
}

class _AddSchoolPageState extends State<AddSchoolPage>
    with WidgetsBindingObserver {
  final _formKey = GlobalKey<FormState>();
  final _scrollController = ScrollController();
  final FocusNode _pageFocusNode = FocusNode();

  // Controllers
  final _schoolNameController = TextEditingController();
  final _emisCodeController = TextEditingController();
  final _communityController = TextEditingController();
  final _principalNameController = TextEditingController();
  final _contactController = TextEditingController();
  final _emailController = TextEditingController();
  final _permitNumberController = TextEditingController();
  final _latitudeController = TextEditingController();
  final _longitudeController = TextEditingController();
  final _teachersPresentController = TextEditingController();
  final _verifyCommentController = TextEditingController();
  final _yearEstablishedController = TextEditingController();
  final _noRoomController = TextEditingController();

  // Selections
  String? _selectedCounty;
  String? _selectedDistrict;
  String? _selectedLevel;
  String? _selectedType;
  String? _selectedOwnership;
  String? _permitStatus = 'No';
  String? _teachersPresent = 'Yes';
  String? _chargeFees = 'Yes';
  String? _consent = 'No';
  String? _schoolClosed = 'Yes';
  String? _firstAssessment = 'Yes';

  bool _isTvet = false;
  bool _isAccelerated = false;
  bool _isAlternative = false;
  bool _isInclusive = false;

  bool _isGettingLocation = false;
  bool _isCountyLoaded = false;
  bool _isGeneratingSchoolCode = false;

  String _autoGeneratedSchoolCode = '';

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);

    WidgetsBinding.instance.addPostFrameCallback((_) {
      _loadDropdownsFromCache();
      context.read<SchoolProvider>().fetchDropdownData(context);
      _loadUserCounty();
      _refreshSchoolCode();
      if (mounted) {
        _pageFocusNode.requestFocus();
      }
    });

    _getCurrentLocation();
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    _pageFocusNode.dispose();
    _schoolNameController.dispose();
    _emisCodeController.dispose();
    _communityController.dispose();
    _principalNameController.dispose();
    _contactController.dispose();
    _emailController.dispose();
    _permitNumberController.dispose();
    _latitudeController.dispose();
    _longitudeController.dispose();
    _teachersPresentController.dispose();
    _verifyCommentController.dispose();
    _yearEstablishedController.dispose();
    _noRoomController.dispose();
    _scrollController.dispose();
    super.dispose();
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    super.didChangeAppLifecycleState(state);
    if (state == AppLifecycleState.resumed) {
      _refreshSchoolCode();
    }
  }

  Future<void> _refreshSchoolCode() async {
    if (_isGeneratingSchoolCode || !mounted) return;

    _isGeneratingSchoolCode = true;
    try {
      await _generateSchoolCode();
    } finally {
      _isGeneratingSchoolCode = false;
    }
  }

  void _loadDropdownsFromCache() {
    final provider = context.read<SchoolProvider>();
    provider.loadFromCache();
  }

  Future<void> _loadUserCounty() async {
    final provider = context.read<SchoolProvider>();
    final county = await provider.fetchUserCounty(context);

    if (county != null && mounted) {
      setState(() {
        _selectedCounty = county;
        _isCountyLoaded = true;
      });

      provider.fetchDistricts(county, context);
    }
  }

  Future<void> _generateSchoolCode() async {
    final authProvider = Provider.of<AuthProvider>(context, listen: false);
    final userIdFormatted = authProvider.getFormattedUserId();
    final timestamp = DateTime.now().millisecondsSinceEpoch.toString();

    if (!mounted) return;

    setState(() {
      _autoGeneratedSchoolCode = 'MOE-$userIdFormatted-$timestamp';
    });

    debugPrint('Generated timestamp-based school code: $_autoGeneratedSchoolCode');
  }

  Future<void> _getCurrentLocation() async {
    if (!mounted) return;

    setState(() => _isGettingLocation = true);

    try {
      bool serviceEnabled = await Geolocator.isLocationServiceEnabled();
      if (!serviceEnabled) {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text(
                'Location services are disabled. Please enable them.',
              ),
              backgroundColor: Colors.orange,
            ),
          );
        }
        return;
      }

      LocationPermission permission = await Geolocator.checkPermission();
      if (permission == LocationPermission.denied) {
        permission = await Geolocator.requestPermission();
        if (permission == LocationPermission.denied) {
          if (mounted) {
            ScaffoldMessenger.of(context).showSnackBar(
              const SnackBar(
                content: Text('Location permission denied. Cannot get GPS.'),
                backgroundColor: Colors.orange,
              ),
            );
          }
          return;
        }
      }

      if (permission == LocationPermission.deniedForever) {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text(
                'Location permission permanently denied. Enable in settings.',
              ),
              backgroundColor: Colors.orange,
            ),
          );
        }
        return;
      }

      Position position = await Geolocator.getCurrentPosition(
        desiredAccuracy: LocationAccuracy.high,
      );

      if (mounted) {
        setState(() {
          _latitudeController.text = position.latitude.toStringAsFixed(6);
          _longitudeController.text = position.longitude.toStringAsFixed(6);
        });
      }
    } catch (e) {
      debugPrint('GPS error: $e');
    } finally {
      if (mounted) {
        setState(() => _isGettingLocation = false);
      }
    }
  }

  bool get _isSchoolClosed => _schoolClosed == 'Yes';
  bool get _showCompliance => !_isSchoolClosed;
  bool get _hasConsent => _consent == 'Yes';

  Future<void> _submitForm() async {
    if (!_formKey.currentState!.validate()) return;

    final provider = context.read<SchoolProvider>();
    final now = DateTime.now();

    debugPrint('Current schoolClosed value before submission: $_schoolClosed');

    if (_isSchoolClosed || (_showCompliance && !_hasConsent)) {
      final minimalSchoolData = <String, dynamic>{
        'county': _selectedCounty,
        'district': _selectedDistrict,
        'school_level': _selectedLevel,
        'school_type': _selectedType,
        'school_ownership': _selectedOwnership,
        'school_closed': _schoolClosed,
        'community': _communityController.text.trim(),
        'school_code': _autoGeneratedSchoolCode,
        'school_name': _schoolNameController.text.trim(),
        'latitude': double.tryParse(_latitudeController.text.trim()),
        'longitude': double.tryParse(_longitudeController.text.trim()),
        'first_assessment': _firstAssessment,
        'date': now.toIso8601String(),
      };

      if (_showCompliance) {
        minimalSchoolData['compliance'] = _consent;
      }

      debugPrint(
        'Submitting minimal school data (school closed or no consent): $minimalSchoolData',
      );

      try {
        final result = await provider.createSchool(minimalSchoolData, context);

        if (!mounted) return;

        if (result['success'] == true) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text(
                result['offline'] == true
                    ? 'School saved offline'
                    : 'School registered successfully!',
              ),
              backgroundColor:
              result['offline'] == true ? Colors.orange : Colors.green,
              duration: const Duration(seconds: 2),
            ),
          );

          await Future.delayed(const Duration(seconds: 2));
          if (mounted) {
            context.push(
              '/assessment-complete',
              extra: {
                'isOffline': result['offline'] == true,
                'schoolName': _schoolNameController.text.trim(),
              },
            );
          }
        } else {
          _showErrorDialog(
            result['message'] ?? 'Failed to create school: Server error',
          );
        }
      } catch (e) {
        debugPrint('Submission error: $e');
        if (mounted) {
          _showErrorDialog('Failed to save: ${e.toString()}');
        }
      }
      return;
    }

    final schoolData = <String, dynamic>{
      'county': _selectedCounty,
      'district': _selectedDistrict,
      'school_level': _selectedLevel,
      'school_type': _selectedType,
      'school_ownership': _selectedOwnership,
      'school_closed': _schoolClosed,
      'community': _communityController.text.trim(),
      'school_code': _autoGeneratedSchoolCode,
      'school_name': _schoolNameController.text.trim(),
      'latitude': double.tryParse(_latitudeController.text.trim()),
      'longitude': double.tryParse(_longitudeController.text.trim()),
      'first_assessment': _firstAssessment,
      'created_at': now.toIso8601String(),
      'updated_at': now.toIso8601String(),
    };

    if (_showCompliance) {
      schoolData['compliance'] = _consent;
    }

    if (_showCompliance && _hasConsent) {
      schoolData.addAll({
        'emis_code': _emisCodeController.text.trim(),
        'tvet': _isTvet ? '1' : '0',
        'accelerated': _isAccelerated ? '1' : '0',
        'alternative': _isAlternative ? '1' : '0',
        'inclusive': _isInclusive ? '1' : '0',
        'year_establish': int.tryParse(_yearEstablishedController.text.trim()),
        'permit': _permitStatus,
        'permit_num':
        _permitStatus == 'Yes'
            ? _permitNumberController.text.trim()
            : null,
        'principal_name': _principalNameController.text.trim(),
        'school_contact': _contactController.text.trim(),
        'email': _emailController.text.trim(),
        'all_teacher_present': _teachersPresent,
        'verify_comment': _verifyCommentController.text.trim(),
        'charge_fees': _chargeFees,
        'nb_room': int.tryParse(_noRoomController.text.trim()) ?? 0,
      });
    }

    debugPrint('Submitting full school data: $schoolData');

    try {
      final result = await provider.createSchool(schoolData, context);

      if (!mounted) return;

      if (result['success'] == true) {
        final String schoolCode =
            result['data']?['school_code'] ?? _autoGeneratedSchoolCode;
        final String schoolName =
            result['data']?['school_name'] ??
                _schoolNameController.text.trim();
        final String schoolLevel =
            result['data']?['school_level'] ?? _selectedLevel ?? 'Unknown';

        if (result['offline'] == true) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text(
                result['message'] ?? 'Saved offline — will sync later',
              ),
              backgroundColor: Colors.orange,
              duration: const Duration(seconds: 4),
            ),
          );
        } else {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text(
                'School registered successfully! Redirecting to Assessment 2...',
              ),
              backgroundColor: Colors.green,
              duration: Duration(seconds: 2),
            ),
          );
        }

        await Future.delayed(const Duration(seconds: 2));
        if (mounted) {
          context.push(
            '/assessment-2',
            extra: {
              'schoolCode': schoolCode,
              'schoolName': schoolName,
              'level': schoolLevel,
              'firstAssessment': _firstAssessment,
            },
          );
        }
      } else {
        _showErrorDialog(
          result['message'] ?? 'Failed to create school: Server error',
        );
      }
    } catch (e) {
      debugPrint('Submission error: $e');
      if (mounted) {
        _showErrorDialog('Failed to save: ${e.toString()}');
      }
    }
  }

  void _showErrorDialog(String message) {
    showDialog(
      context: context,
      builder: (dialogContext) {
        return AlertDialog(
          icon: const Icon(Icons.error, color: Colors.red, size: 64),
          title: const Text('Error'),
          content: Text(message),
          actions: [
            TextButton(
              onPressed: () {
                Navigator.of(dialogContext).pop();
              },
              child: const Text('OK'),
            ),
          ],
        );
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    final provider = context.watch<SchoolProvider>();

    return Focus(
      focusNode: _pageFocusNode,
      autofocus: true,
      onFocusChange: (hasFocus) {
        if (hasFocus) {
          _refreshSchoolCode();
        }
      },
      child: Scaffold(
        appBar: CustomAppBar(
          title: 'Add New School - School Data Summary',
          backgroundColor: AppColors.primary,
          textColor: Colors.white,
          leading: IconButton(
            icon: const Icon(
              Icons.arrow_back_ios_new_rounded,
              color: Colors.white,
            ),
            onPressed: () => context.pop(),
          ),
          actions: [
            IconButton(
              icon: const Icon(Icons.sync, color: Colors.white),
              tooltip: 'Home',
              onPressed: () => context.push('/offline-students'),
            ),
          ],
        ),
        body: LoadingOverlay(
          isLoading: provider.isLoading,
          child: GestureDetector(
            onTap: () => FocusScope.of(context).unfocus(),
            child: Column(
              children: [
                StreamBuilder<bool>(
                  stream: LocalStorageService.onlineStatusStream,
                  initialData: true,
                  builder: (context, snapshot) {
                    final bool isOnline = snapshot.data ?? true;
                    if (!isOnline) {
                      return Container(
                        width: double.infinity,
                        color: Colors.orange.shade100,
                        padding: const EdgeInsets.all(12),
                        child: const Text(
                          'Offline Mode — Data will be saved locally and sync later',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: Colors.deepOrange,
                            fontWeight: FontWeight.w600,
                          ),
                        ),
                      );
                    }
                    return const SizedBox.shrink();
                  },
                ),

                Expanded(
                  child: SingleChildScrollView(
                    controller: _scrollController,
                    padding: const EdgeInsets.fromLTRB(20, 16, 20, 40),
                    child: Form(
                      key: _formKey,
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.stretch,
                        children: [
                          _buildSectionCard(
                            title: 'Location',
                            children: [
                              TextFormField(
                                initialValue: _selectedCounty,
                                decoration: InputDecoration(
                                  labelText:
                                  _selectedCounty != null
                                      ? 'County: $_selectedCounty'
                                      : 'County',
                                  border: const OutlineInputBorder(),
                                  filled: true,
                                  fillColor: Colors.grey.shade100,
                                  hintText:
                                  _isCountyLoaded
                                      ? null
                                      : 'Loading county...',
                                ),
                                enabled: false,
                                validator:
                                    (v) =>
                                _selectedCounty == null
                                    ? 'County not loaded'
                                    : null,
                              ),
                              const SizedBox(height: 16),

                              DropdownButtonFormField<String>(
                                value: _selectedDistrict,
                                decoration: const InputDecoration(
                                  labelText: 'District *',
                                  border: OutlineInputBorder(),
                                ),
                                items:
                                provider.districts.isEmpty
                                    ? [
                                  DropdownMenuItem(
                                    value: null,
                                    child: Text(
                                      _selectedCounty == null
                                          ? 'Loading county...'
                                          : provider.isLoadingDistricts
                                          ? 'Loading districts...'
                                          : 'No districts available',
                                    ),
                                  ),
                                ]
                                    : provider.districts.map((m) {
                                  return DropdownMenuItem<String>(
                                    value:
                                    m['d_name']?.toString() ?? '',
                                    child: Text(
                                      m['d_name']?.toString() ??
                                          'Unknown',
                                    ),
                                  );
                                }).toList(),
                                onChanged:
                                    (v) =>
                                    setState(() => _selectedDistrict = v),
                                validator: (v) => v == null ? 'Required' : null,
                              ),
                              const SizedBox(height: 16),

                              CustomTextField(
                                controller: _communityController,
                                label: 'Community / Village',
                              ),
                              const SizedBox(height: 16),

                              Row(
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Expanded(
                                    child: CustomTextField(
                                      controller: _latitudeController,
                                      label: 'Latitude *',
                                      readOnly: true,
                                      decoration: InputDecoration(
                                        border: const OutlineInputBorder(),
                                        filled: true,
                                        fillColor: Colors.grey.shade100,
                                      ),
                                      validator: (value) {
                                        if (value == null ||
                                            value.trim().isEmpty) {
                                          return 'Latitude is required';
                                        }
                                        if (double.tryParse(value.trim()) ==
                                            null) {
                                          return 'Invalid latitude';
                                        }
                                        return null;
                                      },
                                    ),
                                  ),
                                  const SizedBox(width: 16),
                                  Expanded(
                                    child: CustomTextField(
                                      controller: _longitudeController,
                                      label: 'Longitude *',
                                      readOnly: true,
                                      decoration: InputDecoration(
                                        border: const OutlineInputBorder(),
                                        filled: true,
                                        fillColor: Colors.grey.shade100,
                                      ),
                                      validator: (value) {
                                        if (value == null ||
                                            value.trim().isEmpty) {
                                          return 'Longitude is required';
                                        }
                                        if (double.tryParse(value.trim()) ==
                                            null) {
                                          return 'Invalid longitude';
                                        }
                                        return null;
                                      },
                                    ),
                                  ),
                                ],
                              ),
                              const SizedBox(height: 8),
                              if (_isGettingLocation)
                                const Text(
                                  'Getting current location...',
                                  style: TextStyle(
                                    color: Colors.grey,
                                    fontSize: 12,
                                  ),
                                )
                              else
                                Text(
                                  'Location captured from device GPS',
                                  style: Theme.of(
                                    context,
                                  ).textTheme.bodySmall?.copyWith(
                                    color: Colors.grey[600],
                                    fontStyle: FontStyle.italic,
                                  ),
                                ),
                              if (provider.isLoadingDistricts &&
                                  _selectedCounty != null)
                                const Padding(
                                  padding: EdgeInsets.only(top: 8),
                                  child: Text(
                                    'Refreshing districts in background...',
                                    style: TextStyle(
                                      fontSize: 12,
                                      color: Colors.grey,
                                    ),
                                  ),
                                ),
                            ],
                          ),

                          _buildSectionCard(
                            title: 'School Identity',
                            children: [
                              CustomTextField(
                                controller: _schoolNameController,
                                label: 'School Name *',
                                validator:
                                    (v) =>
                                v?.trim().isEmpty ?? true
                                    ? 'Required'
                                    : null,
                              ),
                              const SizedBox(height: 16),

                              DropdownButtonFormField<String>(
                                value: _selectedLevel,
                                decoration: const InputDecoration(
                                  labelText: 'School Level *',
                                  border: OutlineInputBorder(),
                                  contentPadding: EdgeInsets.symmetric(
                                    horizontal: 16,
                                    vertical: 16,
                                  ),
                                ),
                                items:
                                provider.levels.isEmpty
                                    ? [
                                  const DropdownMenuItem(
                                    value: null,
                                    child: Text('Loading levels...'),
                                  ),
                                ]
                                    : provider.levels.map((level) {
                                  return DropdownMenuItem<String>(
                                    value:
                                    level['code']?.toString() ?? '',
                                    child: Text(
                                      level['name']?.toString() ??
                                          'Unknown',
                                    ),
                                  );
                                }).toList(),
                                onChanged:
                                    (v) => setState(() => _selectedLevel = v),
                                validator: (v) => v == null ? 'Required' : null,
                              ),
                              const SizedBox(height: 16),

                              _dropdown(
                                label: 'School Type *',
                                value: _selectedType,
                                items:
                                provider.types.isEmpty
                                    ? ['Loading...']
                                    : provider.types
                                    .map(
                                      (m) =>
                                  m['name']?.toString() ??
                                      'Unknown',
                                )
                                    .toList(),
                                onChanged: (v) {
                                  if (v != 'Loading...' && v != null) {
                                    setState(() => _selectedType = v);
                                  }
                                },
                                validator:
                                    (v) =>
                                v == null || v == 'Loading...'
                                    ? 'Required'
                                    : null,
                              ),
                              const SizedBox(height: 16),

                              _dropdown(
                                label: 'Ownership *',
                                value: _selectedOwnership,
                                items:
                                provider.ownerships.isEmpty
                                    ? ['Loading...']
                                    : provider.ownerships
                                    .map(
                                      (m) =>
                                  m['name']?.toString() ??
                                      'Unknown',
                                )
                                    .toList(),
                                onChanged: (v) {
                                  if (v != 'Loading...' && v != null) {
                                    setState(() => _selectedOwnership = v);
                                  }
                                },
                                validator:
                                    (v) =>
                                v == null || v == 'Loading...'
                                    ? 'Required'
                                    : null,
                              ),
                              const SizedBox(height: 24),

                              DropdownButtonFormField<String>(
                                key: ValueKey(
                                  'school_closed_${_schoolClosed}',
                                ),
                                value: _schoolClosed,
                                decoration: const InputDecoration(
                                  labelText: 'Is school Closed?',
                                  border: OutlineInputBorder(),
                                ),
                                items:
                                const ['Yes', 'No']
                                    .map(
                                      (item) => DropdownMenuItem<String>(
                                    value: item,
                                    child: Text(item),
                                  ),
                                )
                                    .toList(),
                                onChanged: (v) {
                                  setState(() {
                                    _schoolClosed = v;
                                    if (_isSchoolClosed) {
                                      _consent = 'No';
                                    }
                                  });
                                },
                              ),
                              const SizedBox(height: 16),

                              if (_showCompliance) ...[
                                DropdownButtonFormField<String>(
                                  key: ValueKey('consent_${_consent}'),
                                  value: _consent,
                                  decoration: const InputDecoration(
                                    labelText:
                                    'Is administration available to provide information? *',
                                    border: OutlineInputBorder(),
                                  ),
                                  items:
                                  const ['Yes', 'No']
                                      .map(
                                        (item) =>
                                        DropdownMenuItem<String>(
                                          value: item,
                                          child: Text(item),
                                        ),
                                  )
                                      .toList(),
                                  onChanged: (v) => setState(() => _consent = v),
                                  validator:
                                      (v) => v == null ? 'Required' : null,
                                ),
                              ],
                            ],
                          ),

                          if (_showCompliance && _hasConsent) ...[
                            _buildSectionCard(
                              title: 'Classification',
                              children: [
                                CustomTextField(
                                  controller: _emisCodeController,
                                  label: 'EMIS Code (Optional)',
                                  keyboardType: TextInputType.text,
                                ),
                                const SizedBox(height: 16),

                                CustomTextField(
                                  controller: _noRoomController,
                                  label: 'Number of Rooms *',
                                  keyboardType: TextInputType.number,
                                  validator: (v) {
                                    if (v == null || v.trim().isEmpty) {
                                      return 'Required';
                                    }
                                    if (int.tryParse(v.trim()) == null) {
                                      return 'Enter a valid number';
                                    }
                                    return null;
                                  },
                                ),
                                const SizedBox(height: 16),

                                SwitchListTile(
                                  title: const Text('Offers TVET Program'),
                                  value: _isTvet,
                                  onChanged: (v) => setState(() => _isTvet = v),
                                  activeColor: AppColors.primary,
                                ),
                                SwitchListTile(
                                  title: const Text(
                                    'Accelerated Learning Program',
                                  ),
                                  value: _isAccelerated,
                                  onChanged:
                                      (v) =>
                                      setState(() => _isAccelerated = v),
                                  activeColor: AppColors.primary,
                                ),
                                SwitchListTile(
                                  title: const Text('Alternative Education'),
                                  value: _isAlternative,
                                  onChanged:
                                      (v) =>
                                      setState(() => _isAlternative = v),
                                  activeColor: AppColors.primary,
                                ),
                                SwitchListTile(
                                  title: const Text(
                                    'Inclusive and Special School',
                                  ),
                                  value: _isInclusive,
                                  onChanged:
                                      (v) =>
                                      setState(() => _isInclusive = v),
                                  activeColor: AppColors.primary,
                                ),
                              ],
                            ),

                            _buildSectionCard(
                              title: 'Establishment & Permit',
                              children: [
                                _yearDropdown(),
                                const SizedBox(height: 16),
                                _dropdown(
                                  label: 'Permit Status',
                                  value: _permitStatus,
                                  items: const ['Yes', 'No', 'Pending'],
                                  onChanged:
                                      (v) => setState(() => _permitStatus = v),
                                ),
                                if (_permitStatus == 'Yes') ...[
                                  const SizedBox(height: 16),
                                  CustomTextField(
                                    controller: _permitNumberController,
                                    label: 'Permit Number *',
                                    validator:
                                        (v) =>
                                    v?.trim().isEmpty ?? true
                                        ? 'Required when permit is Yes'
                                        : null,
                                  ),
                                ],
                              ],
                            ),

                            _buildSectionCard(
                              title: 'Contact',
                              children: [
                                CustomTextField(
                                  controller: _principalNameController,
                                  label: 'Principal / Head Teacher Name *',
                                  validator:
                                      (v) =>
                                  v == null || v.trim().isEmpty
                                      ? 'Principal / Head Teacher name is required'
                                      : null,
                                ),
                                const SizedBox(height: 16),
                                CustomTextField(
                                  controller: _contactController,
                                  label: 'School Contact Phone *',
                                  keyboardType: TextInputType.phone,
                                  validator:
                                      (v) =>
                                  v == null || v.trim().isEmpty
                                      ? 'School contact phone is required'
                                      : null,
                                ),
                                const SizedBox(height: 16),
                                CustomTextField(
                                  controller: _emailController,
                                  label: 'School Email',
                                  keyboardType: TextInputType.emailAddress,
                                ),
                              ],
                            ),

                            const SizedBox(height: 24),
                            _buildSectionCard(
                              title: 'Assessment Information',
                              children: [
                                DropdownButtonFormField<String>(
                                  value: _firstAssessment,
                                  decoration: const InputDecoration(
                                    labelText:
                                    'Is this your first assessment at this school?',
                                    border: OutlineInputBorder(),
                                  ),
                                  items:
                                  const ['Yes', 'No']
                                      .map(
                                        (item) =>
                                        DropdownMenuItem<String>(
                                          value: item,
                                          child: Text(item),
                                        ),
                                  )
                                      .toList(),
                                  onChanged: (v) {
                                    setState(() {
                                      _firstAssessment = v;
                                    });
                                  },
                                ),
                              ],
                            ),
                          ],

                          const SizedBox(height: 40),

                          SizedBox(
                            height: 56,
                            child: ElevatedButton.icon(
                              icon: const Icon(Icons.save_rounded),
                              label: const Text(
                                'Submit School',
                                style: TextStyle(
                                  fontSize: 17,
                                  fontWeight: FontWeight.w600,
                                ),
                              ),
                              onPressed: provider.isLoading ? null : _submitForm,
                              style: ElevatedButton.styleFrom(
                                backgroundColor: AppColors.primary,
                                foregroundColor: Colors.white,
                                shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.circular(16),
                                ),
                                elevation: 3,
                              ),
                            ),
                          ),

                          const SizedBox(height: 80),
                        ],
                      ),
                    ),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }

  Widget _buildSectionCard({
    required String title,
    required List<Widget> children,
  }) {
    return Card(
      elevation: 2,
      margin: const EdgeInsets.only(bottom: 24),
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
      child: Padding(
        padding: const EdgeInsets.all(20),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              title,
              style: Theme.of(context).textTheme.titleLarge?.copyWith(
                color: AppColors.primary,
                fontFamily: 'RobotoSlabBold',
              ),
            ),
            const SizedBox(height: 20),
            ...children,
          ],
        ),
      ),
    );
  }

  Widget _dropdown({
    required String label,
    required String? value,
    List<String> items = const [],
    required ValueChanged<String?> onChanged,
    String? Function(String?)? validator,
  }) {
    return DropdownButtonFormField<String>(
      value: value,
      decoration: const InputDecoration(
        border: OutlineInputBorder(),
        contentPadding: EdgeInsets.symmetric(horizontal: 16, vertical: 16),
      ).copyWith(labelText: label),
      items:
      items.map((item) {
        return DropdownMenuItem<String>(value: item, child: Text(item));
      }).toList(),
      onChanged: onChanged,
      validator: validator,
    );
  }

  Widget _yearDropdown() {
    final currentYear = DateTime.now().year;
    final years =
    List.generate(
      currentYear - 1820,
          (index) => (currentYear - index).toString(),
    )..sort((a, b) => b.compareTo(a));

    return DropdownButtonFormField<String>(
      value:
      _yearEstablishedController.text.isNotEmpty
          ? _yearEstablishedController.text
          : null,
      decoration: const InputDecoration(
        labelText: 'Year Established *',
        border: OutlineInputBorder(),
        contentPadding: EdgeInsets.symmetric(horizontal: 16, vertical: 16),
      ),
      items:
      years.map((year) {
        return DropdownMenuItem<String>(value: year, child: Text(year));
      }).toList(),
      onChanged: (value) {
        if (value != null) {
          _yearEstablishedController.text = value;
        }
      },
      validator:
      _hasConsent ? (v) => v == null ? 'Please select a year' : null : null,
    );
  }
}